### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by IcelandicCenterArtificialIntelligence** [Limbicnation/ComfyUIDepthEstimation#4]
It seems the custom node has import issues. 
After trying to install it with the Manager, it installs directly in the custom_nodes folder, instead of its own nested folder there, and also it's missing a __init__.py file.
Not sure about it, but it seems that should be the standard way to have a custom node in ComfyUI, right?

The first import error was about missing comfy.modules and, after putting it into a folder, then it was missing the __init__.py file.

**Comment by Limbicnation** [comment]
@IcelandicCenterArtificialIntelligence Sorry for the late reply! I've fixed the import issues you reported:

Added proper nested folder structure
Created the missing init.py file
Fixed the ComfyUI module imports

Please update to the latest version and let me know if you encounter any other issues! Thanks for reporting this.
